### ISSUE TITLE
Table Support

### ISSUE THREAD

**Issue by cy6erlion** [Michael-F-Bryan/markedit#4]
Hi, thank you for creating Markedit, it is awesome :smiley:!

I have a bit of an issue, whenever I try to `rewrite` markdown that contains a table
it gets escaped.

**Original:**
```text
| Sun | Moon | Earth |                                                                                                              
|-----|------|-------| 
```
**Mutated:**
```text
\| Sun | Moon | Earth |                                                                                                              
\|-----|------|-------| 
```
Is there a way to prevent escaping tables?

**Comment by Michael-F-Bryan** [comment]
How are you creating the original events? I have a feeling `pulldown-cmark` isn't reading the tables, so you might need to enable the [`ENABLE_TABLES`](https://docs.rs/pulldown-cmark/0.7.1/pulldown_cmark/struct.Options.html#associatedconstant.ENABLE_TABLES) option when creating your `Parser`.

If that doesn't work, can you paste a minimal example so I can try it locally?

**Comment by cy6erlion** [comment]
I am also using [pulldown-cmark-to-cmark](https://github.com/Byron/pulldown-cmark-to-cmark) to render the output back to markdown. Here is a code snippet:

```rust
pub fn insert_after<'a>(src: String, after_string: &str, new_string: &str)
                        -> String{
    let matcher = Heading::with_level(1).falling_edge();
    let rule = markedit::insert_markdown_before("## Heading 2", matcher);
    let events = markedit::parse(&src);
    let mutated: Vec<_> = markedit::rewrite(events, rule).collect();


    let mut buf = String::with_capacity(src.len() + 128);
    
    cmark(
        mutated.iter(),
        &mut buf,
        None
    )
        .unwrap();

    buf
}
```

**Comment by Michael-F-Bryan** [comment]
The `markedit::parse()` function is just a helper that [calls `pulldown_cmark::Parser::new()`](https://github.com/Michael-F-Bryan/markedit/blob/b1cbec0bcfa06dc24635d2601d21926327685be2/src/lib.rs#L96). Try constructing the `Parser` and setting its options manually.

**Comment by cy6erlion** [comment]
Fixed it by using `let events = Parser::new_ext(&src, Options::ENABLE_TABLES)`. Thank you :smiley:
